In [1]:
!pip install ipynb

Requirement already satisfied: ipynb in ./rapids-cuml/lib/python3.10/site-packages (0.5.1)

In [2]:
import torch
import gc

In [3]:
from ipynb.fs.full.Normalization_to_import import *

Execution time: 0.6311225891113281 seconds

In [4]:
from ipynb.fs.full.Data_Generation_to_import import *

Execution time: 0.040879011154174805 seconds

In [5]:
from ipynb.fs.full.Machine_Learning_to_import import *

Execution time: 311.5813443660736 seconds
Metrics for not normalized data is ready. Run 'metrics.main()'!
Execution time: 307.06371545791626 seconds
Metrics for maxAbsScaler normalized data is ready. Run 'metrics_maxAbsScaler.main()'!
Execution time: 304.40944170951843 seconds
Metrics for MinMaxScaler normalized data is ready. Run 'metrics_MinMaxScaler.main()'!
Execution time: 312.8728289604187 seconds
Metrics for normalizer normalized data is ready. Run 'metrics_normalizer.main()'!
Execution time: 311.0563747882843 seconds
Metrics for robust_scaler normalized data is ready. Run 'metrics_robust_scaler.main()'!
Execution time: 330.75009393692017 seconds
Metrics for standard_scaler normalized data is ready. Run 'metrics_standard_scaler.main()'!
Execution time: 350.5067844390869 seconds
Metrics for binarizer normalized data is ready. Run 'metrics_binarizer.main()'!
Execution time: 361.9610676765442 seconds
Metrics for function_transformer normalized data is ready. Run 'metrics_function_transformer.main()'!
Execution time: 352.660760641098 seconds
Metrics for KBinsDiscretizer normalized data is ready. Run 'metrics_KBinsDiscretizer.main()'!

In [6]:
torch.cuda.empty_cache()
gc.collect()

0

In [7]:
from ipynb.fs.full.Naive_Bayes_to_import import *

/home/xy/Desktop/ml/rapids-cuml/lib/python3.10/site-packages/cuml/naive_bayes/naive_bayes.py:1563: UserWarning: X dtype is not int32. X will be converted, which will increase memory consumption
  warnings.warn(
/home/xy/Desktop/ml/rapids-cuml/lib/python3.10/site-packages/cuml/naive_bayes/naive_bayes.py:1589: UserWarning: X dtype is not int32. X will be converted, which will increase memory consumption
  warnings.warn(

Execution time: 0.2915034294128418 seconds
Metrics for not normalized data is ready. Run 'metrics.main()'!
Execution time: 0.26378393173217773 seconds
Metrics for MaxAbsScaler normalized data is ready. Run 'metrics_MaxAbsScaler.main()'!
Execution time: 0.2619955539703369 seconds
Metrics for MinMaxScaler normalized data is ready. Run 'metrics_MinMaxScaler.main()'!
Execution time: 0.26764512062072754 seconds
Metrics for Normalizer normalized data is ready. Run 'metrics_Normalizer.main()'!
Execution time: 0.2617039680480957 seconds
Metrics for Binarizer normalized data is ready. Run 'metrics_Binarizer.main()'!
Execution time: 0.2628049850463867 seconds
Metrics for FunctionTransformer normalized data is ready. Run 'metrics_FunctionTransformer.main()'!
Execution time: 0.2646903991699219 seconds
Metrics for KBinsDiscretizer normalized data is ready. Run 'metrics_KBinsDiscretizer.main()'!

In [8]:
ml.LogisticRegression()

In [9]:
logr_predict_global_1

        HeartDiseaseorAttack
0                        1.0
1                        1.0
2                        1.0
3                        1.0
4                        1.0
...                      ...
999995                   1.0
999996                   1.0
999997                   1.0
999998                   1.0
999999                   1.0

[1000000 rows x 1 columns]

In [10]:
nb.GaussianNB()

In [11]:
bnb_predict_global_1

        HeartDiseaseorAttack
0                          0
1                          0
2                          0
3                          1
4                          0
...                      ...
999995                     0
999996                     0
999997                     0
999998                     1
999999                     0

[1000000 rows x 1 columns]

In [12]:
gnb_predict_global_1['HeartDiseaseorAttack'].unique()

0    1
1    0
Name: HeartDiseaseorAttack, dtype: int64