In [1]:
!pip install ipynb

Requirement already satisfied: ipynb in ./rapids-cuml/lib/python3.10/site-packages (0.5.1)

In [2]:
import torch
import gc

In [3]:
from ipynb.fs.full.Normalization_to_import import *

Execution time: 0.6484885215759277 seconds

In [4]:
from ipynb.fs.full.Data_Generation_to_import import *

Execution time: 0.04042696952819824 seconds

In [5]:
from ipynb.fs.full.Machine_Learning_to_import import *

Execution time: 311.392982006073 seconds
Metrics for not normalized data is ready. Run 'metrics.main()'!
Execution time: 304.04684567451477 seconds
Metrics for maxAbsScaler normalized data is ready. Run 'metrics_maxAbsScaler.main()'!
Execution time: 305.1290240287781 seconds
Metrics for MinMaxScaler normalized data is ready. Run 'metrics_MinMaxScaler.main()'!
Execution time: 303.71375608444214 seconds
Metrics for normalizer normalized data is ready. Run 'metrics_normalizer.main()'!
Execution time: 301.4035608768463 seconds
Metrics for robust_scaler normalized data is ready. Run 'metrics_robust_scaler.main()'!
Execution time: 303.1597406864166 seconds
Metrics for standard_scaler normalized data is ready. Run 'metrics_standard_scaler.main()'!
Execution time: 307.4506802558899 seconds
Metrics for binarizer normalized data is ready. Run 'metrics_binarizer.main()'!
Execution time: 307.53876519203186 seconds
Metrics for function_transformer normalized data is ready. Run 'metrics_function_transformer.main()'!
Execution time: 306.5572438240051 seconds
Metrics for KBinsDiscretizer normalized data is ready. Run 'metrics_KBinsDiscretizer.main()'!

In [6]:
torch.cuda.empty_cache()
gc.collect()

0

In [7]:
from ipynb.fs.full.Naive_Bayes_to_import import *

/home/xy/Desktop/ml/rapids-cuml/lib/python3.10/site-packages/cuml/naive_bayes/naive_bayes.py:1563: UserWarning: X dtype is not int32. X will be converted, which will increase memory consumption
  warnings.warn(
/home/xy/Desktop/ml/rapids-cuml/lib/python3.10/site-packages/cuml/naive_bayes/naive_bayes.py:1589: UserWarning: X dtype is not int32. X will be converted, which will increase memory consumption
  warnings.warn(

Execution time: 0.2759838104248047 seconds
Metrics for not normalized data is ready. Run 'metrics.main()'!
Execution time: 0.24095964431762695 seconds
Metrics for MaxAbsScaler normalized data is ready. Run 'metrics_MaxAbsScaler.main()'!
Execution time: 0.2455899715423584 seconds
Metrics for MinMaxScaler normalized data is ready. Run 'metrics_MinMaxScaler.main()'!
Execution time: 0.24267911911010742 seconds
Metrics for Normalizer normalized data is ready. Run 'metrics_Normalizer.main()'!
Execution time: 0.24596142768859863 seconds
Metrics for Binarizer normalized data is ready. Run 'metrics_Binarizer.main()'!
Execution time: 0.2454991340637207 seconds
Metrics for FunctionTransformer normalized data is ready. Run 'metrics_FunctionTransformer.main()'!
Execution time: 0.24624323844909668 seconds
Metrics for KBinsDiscretizer normalized data is ready. Run 'metrics_KBinsDiscretizer.main()'!

In [8]:
torch.cuda.empty_cache()
gc.collect()

0

In [9]:
from ipynb.fs.full.Neighbours_to_import import *

Execution time: 15.786527633666992 seconds
Metrics for not normalized data is ready. Run 'neighbours_metrics.main()'!
KNeighborsClassifier:
Mean squared error:
0.10300378429517502


Median Absolute Error:
0.0


R2 Score:
-0.20974482978529707


Accuracy Score:
0.896996215704825


Kl Divergence:
inf


ROC AUC Score:
0.5428584814071655


KNeighborsRegressor:
Mean squared error:
0.07917632469694177


Median Absolute Error:
0.0


R2 Score:
0.0701006754368928


Accuracy Score:
0.5452932828760644


Kl Divergence:
inf


ROC AUC Score:
0.7530961632728577


Execution time: 19.168776750564575 seconds
Metrics for MaxAbsScaler normalized data is ready. Run 'metrics_MaxAbsScaler.main()'!
Execution time: 19.666974782943726 seconds
Metrics for MinMaxScaler normalized data is ready. Run 'metrics_MinMaxScaler.main()'!
Execution time: 19.709964990615845 seconds
Metrics for Normalizer normalized data is ready. Run 'metrics_Normalizer.main()'!
Execution time: 19.77584457397461 seconds
Metrics for Binarizer normalized data is ready. Run 'metrics_Binarizer.main()'!
Execution time: 19.837716817855835 seconds
Metrics for FunctionTransformer normalized data is ready. Run 'metrics_FunctionTransformer.main()'!
Execution time: 19.933648586273193 seconds
Metrics for KBinsDiscretizer normalized data is ready. Run 'metrics_KBinsDiscretizer.main()'!

In [10]:
torch.cuda.empty_cache()
gc.collect()

0

In [11]:
#ml.LogisticRegression()

In [12]:
#logr_predict_global_1

In [13]:
#nb.GaussianNB()

In [14]:
bnb_predict_global_1

        HeartDiseaseorAttack
0                          0
1                          0
2                          0
3                          0
4                          1
...                      ...
999995                     0
999996                     0
999997                     1
999998                     0
999999                     0

[1000000 rows x 1 columns]

In [15]:
gnb_predict_global_1['HeartDiseaseorAttack'].unique()

0    1
1    0
Name: HeartDiseaseorAttack, dtype: int64

In [16]:
knc_predict_global_1

        HeartDiseaseorAttack
0                        1.0
1                        1.0
2                        1.0
3                        1.0
4                        0.0
...                      ...
999995                   1.0
999996                   1.0
999997                   1.0
999998                   1.0
999999                   1.0

[1000000 rows x 1 columns]

In [17]:
knc_predict_global_1['HeartDiseaseorAttack'].unique()

0    1.0
1    0.0
Name: HeartDiseaseorAttack, dtype: float64

In [18]:
neighbours_metrics.main()

KNeighborsClassifier:
Mean squared error:
0.10316146326080101


Median Absolute Error:
0.0


R2 Score:
-0.2115967162449759


Accuracy Score:
0.896838536739199


Kl Divergence:
inf


ROC AUC Score:
0.564012885093689


KNeighborsRegressor:
Mean squared error:
0.0775289737110654


Median Absolute Error:
0.0


R2 Score:
0.08944825913629117


Accuracy Score:
0.5586368653421634


Kl Divergence:
inf


ROC AUC Score:
0.7689622640609741